// packages/renderer/src/components/Keyboard.tsx
import classNames from 'classnames';

type TKeyboardProps = {
  onType?: (command: string | number) => void;
  disabled?: boolean;
};

export default function Keyboard({ onType, disabled = false }: TKeyboardProps) {
  return (
    <section>
      <div className="flex justify-between items-center mb-2">
        <h2 className="font-bold text-lg tracking-tighter uppercase">KEYBOARD</h2>
      </div>
      <div className={classNames('grid grid-cols-3 gap-2', disabled ? 'opacity-30' : '')}>
        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 'RESET', 0, 'CONFIRM'].map((text) => (
          <button
            key={text}
            disabled={disabled}
            onClick={() => onType?.(text)}
            className="btn-solid-small px-2 h-10"
          >
            {text}
          </button>
        ))}
      </div>
    </section>
  );
}

// packages/renderer/src/components/Keyboard.vue
<template>
  <section>
    <div class="flex justify-between items-center mb-2">
      <h2 class="font-bold text-lg tracking-tighter uppercase">KEYBOARD</h2>
    </div>
    <div :class="{ 'grid grid-cols-3 gap-2': true, 'opacity-30': disabled }">
      <button
        v-for="num in [1, 2, 3, 4, 5, 6, 7, 8, 9, 'RESET', 0, 'CONFIRM']"
        :key="num"
        :disabled="disabled"
        class="btn-solid-small px-2 h-10"
        @click="onType(num)"
        v-text="num"
      ></button>
    </div>
  </section>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  props: {
    disabled: {
      type: Boolean,
      default: () => false,
    },
    onType: {
      type: Function,
      default: () => ({}),
    },
  },
})
</script>
